export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'auth/LOGIN_FAILURE';

export const REGISTER_REQUEST = 'auth/REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'auth/REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'auth/REGISTER_FAILURE';

export const LOGOUT = 'auth/LOGOUT';

export const GET_USER_PROFILE_REQUEST = 'auth/GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'auth/GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'auth/GET_USER_PROFILE_FAILURE';

export const RESET_PASSWORD_REQUEST = 'auth/RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'auth/RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'auth/RESET_PASSWORD_FAILURE';

export const RESET_PASSWORD_VERIFY_REQUEST = 'auth/RESET_PASSWORD_VERIFY_REQUEST';
export const RESET_PASSWORD_VERIFY_SUCCESS = 'auth/RESET_PASSWORD_VERIFY_SUCCESS';
export const RESET_PASSWORD_VERIFY_FAILURE = 'auth/RESET_PASSWORD_VERIFY_FAILURE';

export const CLEAR_ERROR = 'auth/CLEAR_ERROR';
